export const CLIENT_ACTION_TYPES = {
  FETCH_CLIENTS: "client/FETCH_CLIENTS",
  SET_CLIENTS: "client/SET_CLIENTS",
  SET_CURRENT_CLIENT: "client/SET_CURRENT_CLIENT",
  SET_LOADING: "client/SET_LOADING",
  SET_ERROR: "client/SET_ERROR",
  UPDATE_CURRENT_CLIENT: "client/UPDATE_CURRENT_CLIENT",
  DELETE_CURRENT_CLIENT: "client/DELETE_CURRENT_CLIENT",
};
